// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVWNxmwunVdUpBgaAbyFdm2JwnQ7PuKMU',
    appId: '1:1086272367125:web:97f83394abd70f3c1bbc1c',
    messagingSenderId: '1086272367125',
    projectId: 'baobao-b0c4c',
    authDomain: 'baobao-b0c4c.firebaseapp.com',
    databaseURL: 'https://baobao-b0c4c-default-rtdb.firebaseio.com',
    storageBucket: 'baobao-b0c4c.firebasestorage.app',
    measurementId: 'G-6T34MJTWK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUHxLD6BIpJp-nLgPqKw3icdZ-XkD6NUE',
    appId: '1:1086272367125:android:14d2098c37fb6a271bbc1c',
    messagingSenderId: '1086272367125',
    projectId: 'baobao-b0c4c',
    databaseURL: 'https://baobao-b0c4c-default-rtdb.firebaseio.com',
    storageBucket: 'baobao-b0c4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH6EAGAd-uWUEnbjUyc6ndd1HtgLDsJ58',
    appId: '1:1086272367125:ios:770a5afd0bd985b51bbc1c',
    messagingSenderId: '1086272367125',
    projectId: 'baobao-b0c4c',
    databaseURL: 'https://baobao-b0c4c-default-rtdb.firebaseio.com',
    storageBucket: 'baobao-b0c4c.firebasestorage.app',
    iosClientId: '1086272367125-6k0kpji9519mmnre1uc3a91vq55ipa0d.apps.googleusercontent.com',
    iosBundleId: 'com.example.baobao',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH6EAGAd-uWUEnbjUyc6ndd1HtgLDsJ58',
    appId: '1:1086272367125:ios:770a5afd0bd985b51bbc1c',
    messagingSenderId: '1086272367125',
    projectId: 'baobao-b0c4c',
    databaseURL: 'https://baobao-b0c4c-default-rtdb.firebaseio.com',
    storageBucket: 'baobao-b0c4c.firebasestorage.app',
    iosClientId: '1086272367125-6k0kpji9519mmnre1uc3a91vq55ipa0d.apps.googleusercontent.com',
    iosBundleId: 'com.example.baobao',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVWNxmwunVdUpBgaAbyFdm2JwnQ7PuKMU',
    appId: '1:1086272367125:web:02e6c8d342f362d11bbc1c',
    messagingSenderId: '1086272367125',
    projectId: 'baobao-b0c4c',
    authDomain: 'baobao-b0c4c.firebaseapp.com',
    databaseURL: 'https://baobao-b0c4c-default-rtdb.firebaseio.com',
    storageBucket: 'baobao-b0c4c.firebasestorage.app',
    measurementId: 'G-VRVT6KTHZB',
  );
}
